### ISSUE TITLE
Pass info on replaced files in callback

### ISSUE THREAD

**Issue by davej** [adambuczynski/replace-in-file#2]
It would be nice if the callback passed an array of what files had changed.

**Comment by adambuczynski** [comment]
Done!

**Comment by davej** [comment]
Awesome, cheers!

**Comment by adambuczynski** [comment]
Make sure to use 0.2.1, as 0.2.0 has a bug in it where it's writing the old contents to the file

**Comment by davej** [comment]
My bad, should have tested the pr before creating it. Thanks!

**Comment by adambuczynski** [comment]
No worries, I've just added 2 tests to make sure any other new additions don't break the main functionality :) Will include some more tests later as well.
