### ISSUE TITLE
Allow globs in `files`

### ISSUE THREAD

**Issue by RyanZim** [adambuczynski/replace-in-file#7]
I would like to use this lib for injecting analytics code into my html.

It would be nice to be able to pass the `files` option as a glob. Example:
```
replace({
    // Glob:
    files: 'path/to/files/*.html',

    replace: '<!-- analytics -->',
    with: `Replacement Code`
});
```

https://github.com/isaacs/node-glob works well for this. I can submit a PR if you want.

**Comment by adambuczynski** [comment]
@RyanZim that seems like a sensible addition. Happy to accept a PR for it.
