### ISSUE TITLE
Browserify can't transform lib with Babelify

### ISSUE THREAD

**Issue by mmustra** [adambuczynski/replace-in-file#9]
Hi  @adambuczynski ,

It seems that Browserify can't transform your lib with Babelify.
But, if I include an option in you package.json, it works fine. 
```
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  }
```

My gulp task:
```
var b = browserify({
  entries: entryPoint,
  transform: [babelify.configure({ presets: ['es2015'] })]
);
b.bundle()
  .pipe(source(exitPoint))
  .pipe(buffer())
  .pipe(uglify())
  .pipe(gulp.dest('./'));
```

Did you experience something similar? Can you maybe update your package.json file with above snippet to fix issue?

Thanks in advance!

**Comment by adambuczynski** [comment]
I have added the suggested snippet to `package.json`, let me know if that works for you. Fixed in 2.0.2 🎉

**Comment by mmustra** [comment]
Hello Adam,

Thanks for prompt response and fix, works like a charm.

Regards!

**Comment by adambuczynski** [comment]
Excellent, thanks
